### ISSUE TITLE
面试突击中，JVM部分

### ISSUE THREAD

**Issue by bourne-3** [Snailclimb/JavaGuide#1416]
面试突击中，JVM部分中的对象的创建过程中。
" 这一步操作保证了对象的实例字段在 Java 代码中可以不赋初始值就直接使用，程序能访问到这些字段的数据类型所对应的零值。"
这一部分的表述不是很理解，不赋初始值就直接使用吗，我刚才试了一下 int i以及 Integer i; 不能够直接使用，显示说需要经过初始化。请问是为啥呢？

**Comment by aexftf** [comment]
你可以试试在另一个类中调用试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月26日(周日) 晚上7:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)




 
面试突击中，JVM部分中的对象的创建过程中。
 " 这一步操作保证了对象的实例字段在 Java 代码中可以不赋初始值就直接使用，程序能访问到这些字段的数据类型所对应的零值。"
 这一部分的表述不是很理解，不赋初始值就直接使用吗，我刚才试了一下 int i以及 Integer i; 不能够直接使用，显示说需要经过初始化。请问是为啥呢？

**Comment by bourne-3** [comment]
您好，已经解决。谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月26日(星期天) 晚上8:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)





 你可以试试在另一个类中调用试一下 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年9月26日(周日) 晚上7:51 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416) 
 
 
 
 
   
 面试突击中，JVM部分中的对象的创建过程中。 
  " 这一步操作保证了对象的实例字段在 Java 代码中可以不赋初始值就直接使用，程序能访问到这些字段的数据类型所对应的零值。" 
  这一部分的表述不是很理解，不赋初始值就直接使用吗，我刚才试了一下 int i以及 Integer i; 不能够直接使用，显示说需要经过初始化。请问是为啥呢？ 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aexftf** [comment]
请问一下你是怎么知道我的联系方式的？😳



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月26日(周日) 晚上8:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)




 您好，已经解决。谢谢 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年9月26日(星期天) 晚上8:14 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; "State ***@***.***&amp;gt;;  
 主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416) 
 
 
 
 
 
  你可以试试在另一个类中调用试一下  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2021年9月26日(周日) 晚上7:51  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;  
  主题: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)  
   
   
   
   
     
  面试突击中，JVM部分中的对象的创建过程中。  
   " 这一步操作保证了对象的实例字段在 Java 代码中可以不赋初始值就直接使用，程序能访问到这些字段的数据类型所对应的零值。"  
   这一部分的表述不是很理解，不赋初始值就直接使用吗，我刚才试了一下 int i以及 Integer i; 不能够直接使用，显示说需要经过初始化。请问是为啥呢？  
     
  —  
  You are receiving this because you are subscribed to this thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 — 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bourne-3** [comment]
我是直接在开的 issue的 我不知道你的联系方式欸...




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月26日(星期天) 晚上8:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)





 请问一下你是怎么知道我的联系方式的？😳 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年9月26日(周日) 晚上8:15 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416) 
 
 
 
 
  您好，已经解决。谢谢  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年9月26日(星期天) 晚上8:14  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; "State ***@***.***&amp;amp;gt;;   
  主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)  
   
   
   
   
   
   你可以试试在另一个类中调用试一下   
     
     
     
   ---原始邮件---   
   发件人: ***@***.***&amp;amp;amp;gt;   
   发送时间: 2021年9月26日(周日) 晚上7:51   
   收件人: ***@***.***&amp;amp;amp;gt;;   
   抄送: ***@***.***&amp;amp;amp;gt;;   
   主题: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)   
     
     
     
     
       
   面试突击中，JVM部分中的对象的创建过程中。   
    " 这一步操作保证了对象的实例字段在 Java 代码中可以不赋初始值就直接使用，程序能访问到这些字段的数据类型所对应的零值。"   
    这一部分的表述不是很理解，不赋初始值就直接使用吗，我刚才试了一下 int i以及 Integer i; 不能够直接使用，显示说需要经过初始化。请问是为啥呢？   
       
   —   
   You are receiving this because you are subscribed to this thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
  —  
  You are receiving this because you modified the open/close state.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aexftf** [comment]
哎白高兴一场





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月26日(周日) 晚上8:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)




 我是直接在开的 issue的 我不知道你的联系方式欸... 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年9月26日(星期天) 晚上8:28 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; "State ***@***.***&amp;gt;;  
 主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416) 
 
 
 
 
 
  请问一下你是怎么知道我的联系方式的？😳  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2021年9月26日(周日) 晚上8:15  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)  
   
   
   
   
   您好，已经解决。谢谢   
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: ***@***.***&amp;amp;amp;gt;;    
   发送时间: 2021年9月26日(星期天) 晚上8:14   
   收件人: ***@***.***&amp;amp;amp;gt;;    
   抄送: ***@***.***&amp;amp;amp;gt;; "State ***@***.***&amp;amp;amp;gt;;    
   主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)   
     
     
     
     
     
    你可以试试在另一个类中调用试一下    
       
       
       
    ---原始邮件---    
    发件人: ***@***.***&amp;amp;amp;amp;gt;    
    发送时间: 2021年9月26日(周日) 晚上7:51    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;    
    抄送: ***@***.***&amp;amp;amp;amp;gt;;    
    主题: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)    
       
       
       
       
         
    面试突击中，JVM部分中的对象的创建过程中。    
     " 这一步操作保证了对象的实例字段在 Java 代码中可以不赋初始值就直接使用，程序能访问到这些字段的数据类型所对应的零值。"    
     这一部分的表述不是很理解，不赋初始值就直接使用吗，我刚才试了一下 int i以及 Integer i; 不能够直接使用，显示说需要经过初始化。请问是为啥呢？    
         
    —    
    You are receiving this because you are subscribed to this thread.    
    Reply to this email directly, view it on GitHub, or unsubscribe.    
   —   
   You are receiving this because you modified the open/close state.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 — 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bourne-3** [comment]
哈哈哈哈哈哈哈哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月26日(星期天) 晚上8:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)





 哎白高兴一场 
 
 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年9月26日(周日) 晚上8:32 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416) 
 
 
 
 
  我是直接在开的 issue的 我不知道你的联系方式欸...  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年9月26日(星期天) 晚上8:28  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; "State ***@***.***&amp;amp;gt;;   
  主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)  
   
   
   
   
   
   请问一下你是怎么知道我的联系方式的？😳   
     
     
     
   ---原始邮件---   
   发件人: ***@***.***&amp;amp;amp;gt;   
   发送时间: 2021年9月26日(周日) 晚上8:15   
   收件人: ***@***.***&amp;amp;amp;gt;;   
   抄送: ***@***.******@***.***&amp;amp;amp;gt;;   
   主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)   
     
     
     
     
    您好，已经解决。谢谢    
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: ***@***.***&amp;amp;amp;amp;gt;;     
    发送时间: 2021年9月26日(星期天) 晚上8:14    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;     
    抄送: ***@***.***&amp;amp;amp;amp;gt;; "State ***@***.***&amp;amp;amp;amp;gt;;     
    主题: Re: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)    
       
       
       
       
       
     你可以试试在另一个类中调用试一下     
         
         
         
     ---原始邮件---     
     发件人: ***@***.***&amp;amp;amp;amp;amp;gt;     
     发送时间: 2021年9月26日(周日) 晚上7:51     
     收件人: ***@***.***&amp;amp;amp;amp;amp;gt;;     
     抄送: ***@***.***&amp;amp;amp;amp;amp;gt;;     
     主题: [Snailclimb/JavaGuide] 面试突击中，JVM部分 (#1416)     
         
         
         
         
           
     面试突击中，JVM部分中的对象的创建过程中。     
      " 这一步操作保证了对象的实例字段在 Java 代码中可以不赋初始值就直接使用，程序能访问到这些字段的数据类型所对应的零值。"     
      这一部分的表述不是很理解，不赋初始值就直接使用吗，我刚才试了一下 int i以及 Integer i; 不能够直接使用，显示说需要经过初始化。请问是为啥呢？     
           
     —     
     You are receiving this because you are subscribed to this thread.     
     Reply to this email directly, view it on GitHub, or unsubscribe.     
    —    
    You are receiving this because you modified the open/close state.    
    Reply to this email directly, view it on GitHub, or unsubscribe.    
    Triage notifications on the go with GitHub Mobile for iOS or Android.    
   —   
   You are receiving this because you commented.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
  —  
  You are receiving this because you modified the open/close state.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
