### ISSUE TITLE
OutOfMemoryError部分描述遗漏

### ISSUE THREAD

**Issue by Acker2015** [Snailclimb/JavaGuide#195]
![image](https://user-images.githubusercontent.com/13566616/53929186-d9e76180-40c7-11e9-92e4-e8eb0273f55d.png)
这里应该是 "OutOfMemoryError： 若 Java 虚拟机栈的内存大小**不允许**动态扩展，且当线程请求栈时内存用完了，无法再动态扩展了，此时抛出OutOfMemoryError异常。"吧

**Comment by gangan786** [comment]
在周志明的深入理解JVM中关于虚拟机栈的描述是这样的：如果虚拟机栈**可以**动态扩展（当前大部分的Java虚拟机都可以动态扩展，只不过Java虚拟机规范中也允许固定长度的虚拟机栈），如果扩展时无法申请到足够的内存，就会抛出OutMemoryError异常
这是官方文档给出的解释：Thrown when the Java Virtual Machine cannot allocate an object because it is out of memory, and no more memory could be made available by the garbage collector. OutOfMemoryError objects may be constructed by the virtual machine as if suppression were disabled and/or the stack trace was not writable.

**Comment by Acker2015** [comment]
> 在周志明的深入理解JVM中关于虚拟机栈的描述是这样的：如果虚拟机栈**可以**动态扩展（当前大部分的Java虚拟机都可以动态扩展，只不过Java虚拟机规范中也允许固定长度的虚拟机栈），如果扩展时无法申请到足够的内存，就会抛出OutMemoryError异常
> 这是官方文档给出的解释：Thrown when the Java Virtual Machine cannot allocate an object because it is out of memory, and no more memory could be made available by the garbage collector. OutOfMemoryError objects may be constructed by the virtual machine as if suppression were disabled and/or the stack trace was not writable.
> 其实这两个异常在概念上是有重合的地方，如果是**不允许**的话，那么就应该抛出StackOverflowError了，我的理解是这样，欢迎指正

翻了翻书，应该是这样的。感谢
